export type ServiceCategory = "automobiles" | "real-estate" | "other";

export interface Organization {
  id: number;
  name: string;
  city: string;
  services: string[];
  category: ServiceCategory;
  description: string;
  rating: number;
  reviews: number;
  priceFrom: number;
  priceTo: number;
  licensed: boolean;
  years: number;
  responseDays: number;
  availabilityDays: number;
  website: string;
  phone: string;
  tags: string[];
}

export const ORGS: Organization[] = [
  {
    id: 1,
    name: "СтройМастер KZ",
    city: "Алматы",
    category: "real-estate",
    description: "Капитальный и косметический ремонт квартир под ключ. Гарантия и договор.",
    services: ["Ремонт под ключ", "Отделка", "Сантехника", "Электрика"],
    rating: 4.8,
    reviews: 214,
    priceFrom: 12000,
    priceTo: 30000,
    licensed: true,
    years: 8,
    responseDays: 1,
    availabilityDays: 5,
    website: "https://demo.example/1",
    phone: "+7 701 123 45 67",
    tags: ["Гарантия 12 мес.", "Без предоплаты"],
  },
  {
    id: 2,
    name: "УютДом Про",
    city: "Астана",
    category: "real-estate",
    description: "Дизайн-проект и реализация. Мебель на заказ, визуализации, сопровождение.",
    services: ["Дизайн‑проект", "Ремонт под ключ", "Мебель на заказ"],
    rating: 4.6,
    reviews: 97,
    priceFrom: 15000,
    priceTo: 42000,
    licensed: true,
    years: 5,
    responseDays: 2,
    availabilityDays: 14,
    website: "https://demo.example/2",
    phone: "+7 702 555 77 88",
    tags: ["3D‑визуализация", "Договор"],
  },
  {
    id: 3,
    name: "ЭлектроСервис",
    city: "Шымкент",
    category: "other",
    description: "Монтаж и ремонт электропроводки, автоматы, щиты, освещение. Срочный выезд.",
    services: ["Электрика"],
    rating: 4.2,
    reviews: 53,
    priceFrom: 8000,
    priceTo: 20000,
    licensed: false,
    years: 3,
    responseDays: 1,
    availabilityDays: 3,
    website: "https://demo.example/3",
    phone: "+7 705 222 11 00",
    tags: ["Срочный выезд"],
  },
  {
    id: 4,
    name: "СантехЛюкс",
    city: "Алматы",
    category: "other",
    description: "Сантехнические работы любой сложности. Установка, замена, ремонт. 24/7.",
    services: ["Сантехника"],
    rating: 4.9,
    reviews: 341,
    priceFrom: 10000,
    priceTo: 25000,
    licensed: true,
    years: 10,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://demo.example/4",
    phone: "+7 700 999 66 55",
    tags: ["24/7", "Гарантия 24 мес."],
  },
  {
    id: 5,
    name: "Окна&Двери KZ",
    city: "Актобе",
    category: "real-estate",
    description: "ПВХ и алюминиевые конструкции. Замер бесплатно, рассрочка, гарантия.",
    services: ["Окна и двери", "Отделка"],
    rating: 4.3,
    reviews: 61,
    priceFrom: 9000,
    priceTo: 38000,
    licensed: true,
    years: 4,
    responseDays: 3,
    availabilityDays: 7,
    website: "https://demo.example/5",
    phone: "+7 707 123 00 11",
    tags: ["Рассрочка", "Замер бесплатно"],
  },
  {
    id: 6,
    name: "AutoPro Сервис",
    city: "Алматы",
    category: "automobiles",
    description: "Техобслуживание, диагностика, ремонт ходовой и тормозной системы.",
    services: ["ТО", "Диагностика", "Ходовая"],
    rating: 4.5,
    reviews: 188,
    priceFrom: 7000,
    priceTo: 35000,
    licensed: true,
    years: 6,
    responseDays: 1,
    availabilityDays: 3,
    website: "https://demo.example/auto1",
    phone: "+7 701 100 20 30",
    tags: ["Гарантия", "Оригинальные запчасти"],
  },
  {
    id: 7,
    name: "Detailing KZ",
    city: "Астана",
    category: "automobiles",
    description: "Детейлинг, полировка, керамика, химчистка салона.",
    services: ["Детейлинг", "Полировка", "Керамика"],
    rating: 4.7,
    reviews: 132,
    priceFrom: 15000,
    priceTo: 80000,
    licensed: false,
    years: 4,
    responseDays: 2,
    availabilityDays: 5,
    website: "https://demo.example/auto2",
    phone: "+7 702 300 40 50",
    tags: ["Запись онлайн"],
  },
  {
    id: 8,
    name: "Шиномонтаж 24",
    city: "Караганда",
    category: "automobiles",
    description: "Шиномонтаж, балансировка, сезонная смена колес 24/7.",
    services: ["Шиномонтаж", "Балансировка"],
    rating: 4.1,
    reviews: 79,
    priceFrom: 3000,
    priceTo: 15000,
    licensed: false,
    years: 7,
    responseDays: 0,
    availabilityDays: 0,
    website: "https://demo.example/auto3",
    phone: "+7 705 555 55 55",
    tags: ["24/7"],
  },
  {
    id: 9,
    name: "РемТехника",
    city: "Атырау",
    category: "other",
    description: "Ремонт бытовой техники: стиральные машины, холодильники, плиты.",
    services: ["Техника"],
    rating: 4.4,
    reviews: 65,
    priceFrom: 6000,
    priceTo: 28000,
    licensed: false,
    years: 5,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://demo.example/oth1",
    phone: "+7 700 800 90 10",
    tags: ["Выезд"],
  },
  {
    id: 10,
    name: "Мастер Мебели",
    city: "Костанай",
    category: "other",
    description: "Сборка и ремонт мебели, регулировка фурнитуры, изготовление деталей.",
    services: ["Мебель"],
    rating: 4.0,
    reviews: 41,
    priceFrom: 5000,
    priceTo: 25000,
    licensed: false,
    years: 3,
    responseDays: 2,
    availabilityDays: 4,
    website: "https://demo.example/oth2",
    phone: "+7 700 700 70 70",
    tags: ["Недорого"],
  },
  {
    id: 11,
    name: "CleanUp Pro",
    city: "Алматы",
    category: "real-estate",
    description: "Клининг квартир и домов, генеральная уборка, после ремонта.",
    services: ["Клининг"],
    rating: 4.6,
    reviews: 112,
    priceFrom: 10000,
    priceTo: 40000,
    licensed: true,
    years: 5,
    responseDays: 1,
    availabilityDays: 2,
    website: "https://demo.example/re1",
    phone: "+7 777 111 22 33",
    tags: ["Эко-средства"],
  },
];

export const CITIES = ["Алматы", "Астана", "Шымкент", "Караганда", "Актобе", "Атырау", "Костанай"];

export const SERVICES = [
  "Ремонт под ключ",
  "Отделка",
  "Сантехника",
  "Электрика",
  "Дизайн‑проект",
  "Мебель на заказ",
  "Окна и двери",
  "Клининг",
];

export const SERVICES_AUTOMOBILES = [
  "ТО",
  "Диагностика",
  "Ходовая",
  "Детейлинг",
  "Полировка",
  "Керамика",
  "Шиномонтаж",
  "Балансировка",
];

export const SERVICES_REAL_ESTATE = [
  "Ремонт под ключ",
  "Отделка",
  "Сантехника",
  "Электрика",
  "Дизайн‑проект",
  "Клининг",
  "Окна и двери",
  "Мебель на заказ",
];

export const SERVICES_OTHER = [
  "Электрика",
  "Сантехника",
  "Техника",
  "Мебель",
];
